#!/bin/bash

#check if dinsar
if [ -e "${sam_in_dem}" ]; then
  echo "I guess you are using external DEM for geocoding."
  echo "I'll run the dem2slant2h (slant2hTrick)."
  dem2slant2h
  [ $? -eq 0 ] && echo "${dorisProcess}: SUCCESS"   
else
  echo "I guess you are trying differential interferometry."
  echo "I'll run the actual DORIS slant2h step."
  pp ${dorisProcess}
  doris ${outputFolder}/${dorisProcess}.drs
  [ $? -eq 0 ] && echo "${dorisProcess}: SUCCESS"
fi
