#!/bin/bash
# USAGE:
#	rs2pn resultfileSection resultfile
#
# DESCRIPTION:
#  RS2PN is an external ADORE command.  
#  It outputs the process name for the given DORIS result file section.
#
# INPUT:
#  resultfileSection: DORIS resultfile section to lookup.
#  Optional:
#     resultfile: Name of the resultfile to define master/slave step.
#  
# OUTPUT:
#  Name of the process name.


[ "$1" == "readfiles" ] && echo m_readfiles
[ "$1" == "readfiles" ] && echo s_readfiles
[ "$1" == "coarse_orbits"   ] && echo coarseorb
[ "$1" == "dem_assist"   ] && echo demassist
[ "$1" == "subtr_refpha"   ] && echo subtrrefphase
[ "$1" == "dinsar"  ] && echo dinsar
[ "$1" == "precise_orbits"  ] && echo m_porbits
[ "$1" == "precise_orbits"  ] && echo s_porbits
[ "$1" == "coarse_correl"  ] && echo coarsecorr
[ "$1" == "comp_coregpm"  ] && echo coregpm
[ "$1" == "comp_refdem"  ] && echo comprefdem
[ "$1" == "slant2h"  ] && echo slant2h
[ "$1" == "crop"  ] && echo m_crop
[ "$1" == "crop"  ] && echo s_crop
[ "$1" == "filt_azi"  ] && echo m_filtazi
[ "$1" == "resample"  ] && echo resample
[ "$1" == "subtr_refdem"  ] && echo subtrrefdem
[ "$1" == "geocoding"  ] && echo geocode
[ "$1" == "sim_amplitude"  ] && echo m_simamp
[ "$1" == "filt_azi"  ] && echo s_filtazi
[ "$1" == "filt_range"  ] && echo filtrange
[ "$1" == "coherence"  ] && echo coherence
[ "$1" == "master_timing"  ] && echo m_timing
[ "$1" == "fine_coreg"  ] && echo fine
[ "$1" == "interfero"  ] && echo interfero
[ "$1" == "filtphase"  ] && echo filtphase
[ "$1" == "oversample"  ] && echo m_ovs
[ "$1" == "oversample"  ] && echo s_ovs
[ "$1" == "timing_error"  ] && echo reltiming
[ "$1" == "comp_refphase"  ] && echo comprefpha
[ "$1" == "unwrap"  ] && echo unwrap
