#!/bin/bash
# USAGE:
#	. undo processName [fileName]
#	. undo processName
#
# DESCRIPTION:
#  UNDO is an internal ADORE command. It removes the 
#  given processName from the result files.   
#
# INPUT:
#  processName: Doris step to be deleted from the resultfile.
#  
#  Optional:
#    fileName: If omitted undo will try to remove the given doris
#      step from master, slave and interferograms result files.    
#
# OUTPUT:
#  Undo Successful: if doris step was found and removed.
#  
# Doris steps in result files.
# readfiles       coarse_orbits  interfero       filtphase
# precise_orbits  coarse_correl  comp_refphase   unwrap
# crop            fine_coreg     subtr_refphase  slant2h
# sim_amplitude   timing_error   comp_refdem     geocoding
# master_timing   dem_assist     subtr_refdem    dinsar
# filt_azi        comp_coregpm   coherence
# filt_range      resample
# oversample
#

dorisProcessReset()
{
## AUTHOR:   Mahmut Arikan
## EMAIL:    M.Arikan@TUDelft.nl
## VERSION:  v1.4
## DATE:     20060612
## UPDATE:   20090114
##
## TUDelft, DEOS Radar Group  - 2006
##
##
## reset doris steps in the result files,
## up to the processing step you want
 
 lineno=$(awk '/_Start_'$1'/{print NR-1}' $2);  # get me the line number of the process line - 1
 if [ "$lineno" != "" ]; then 
   echo "  ${1} found at ${lineno} in ${2}"
   sed -i -e '/^'$1'/,/End_process_control/s/1/0/g' -e ''${lineno}',$ d' $2
   [ $? -eq 0 ] && echo "  Undo Successful."
 else
   echo "  ${1} not found in ${2}. This might not be important."
 fi
}

if [ "${2-undefined}" != "undefined" ]; then
  dorisProcessReset ${1} ${2}
else
  dorisProcessReset ${1} ${m_resfile}
  dorisProcessReset ${1} ${s_resfile}
  dorisProcessReset ${1} ${i_resfile}
fi

