#!/bin/bash
#
# USAGE:
#	? commandName
#
# DESCRIPTION:
#  ? is a builtin ADORE command.  
#  It displays the help for given adore command.   
#
# INPUT:
#  commandName: ADORE command name to get help. A list of commands 
#  can be found at the end of this help message.
#  
# OUTPUT:
#  Help message for the specified command, or this message if no command is given.
# 
# 
# ******ADORE Commands******
# ?		: Help
# check		: Check completed steps in result file.
# dem 		: Create, load and check dem
# dem2slant2h	: Create DORIS slant2h output from comprefdem.
# initialize	: Initialize default settings.
# lsprocess	: list DORIS processes
# mask		: Mask DORIS file using snaphu output. 
# p		: Process DORIS step.
# pn2rs		: convert Process Name to Result file Section title.
# raster		: Create raster image from doris result.
# s		: Show the input file for the DORIS step.
# saveas 	: Export DORIS results to a different format.
# scenes 	: Include and exclude scenes from processing. 
# settings	: Utility for listing, saving and loading ADORE variables.
# undo		: Undo all processing after a given step.

