#!/bin/bash
# USAGE:
#	scenes 
#	scenes exclude orbitFolder1 orbitFolder2 ...
#	scenes include orbitFolder1 orbitFolder2 ...
#	scenes init /path/to/files
#
# DESCRIPTION:
#  SCENES is an internal ADORE command. 
#  It has three usages: 
#
#  scenes: 
#   	With no input parameters all available scenes are shown.
#
#  scenes exclude:
# 	With no inputs this command lists currently excluded scenes.
#
#  scenes exclude orbitFolder1 orbitFolder2 ...:
#       listed orbit folders (folders inside data folder) are excluded from
#       batch processing.
#
# scenes include:
#  	With no inputs this command lists currently included scenes. 
#
# scenes include orbitFolder1 orbitFolder2 ...:
#  	given orbit folders will be removed from the exclude list. 
#
#

function all_scenes(){
  ls -F ${dataFolder}/ 2>/dev/null| grep "/"| tr -d "/"
}

function scenes_exclude(){
  if [ "${1:-undefined}" == "undefined" ];then
    if [ ${#scenes_exclude[@]} -gt 0 ]; then
    #if [ -n "${scenes_exclude}" ]; then
      #echo ${scenes_exclude}
      echo ${scenes_exclude[@]}
    else 
      echo "Currently, no scenes are excluded."
    fi
  else
    local scene
    for scene in "$@"
    do
      if [ -d "${dataFolder}/${scene}" ]; then
        echo "Excluding ${scene}"
        #echo "${orbit}" >> ${excludesFile}
#        scenes_exclude=`echo ${scenes_exclude} ${scene} | tr " " "\n"|sort|tr "\n" " "`;
#        scenes_include="${scenes_include//${scene}/}"; # Remove the given string from includes, add it to the excludes.
 	scenes_exclude=( ${scenes_exclude[@]} ${scene} );
 	scenes_include=( ${scenes_include[@]//${scene}/} );
      else
        echo "Can not find ${scene} in data folder: ${dataFolder}"
        return;
      fi
    done
  fi
}

function scenes_include(){
  if [ "${1:-undefined}" == "undefined" ]; then
    if [ ${#scenes_include[@]} -gt 0 ]; then
    #if [ -n "${scenes_include}" ]; then
#      echo ${scenes_include}
      echo ${scenes_include[@]}
    else
      echo "Currently, there are no scenes included. Check if you have your dataFolder set correctly."  
    fi
  else    
    local scene
    for scene in "$@"  
    do
#      scenes_exclude="${scenes_exclude[@]//${scene}/}"; # Remove the given string from excludes, add it to the includes.
#      scenes_include=`echo ${scenes_include[@]} ${scene} |tr " " "\n"|sort|tr "\n" " "`;
     scenes_exclude=( ${scenes_exclude[@]//${scene}/} );
     scenes_include=( ${scenes_include[@]} ${scene} );
    done
  fi
}

function scenes_init(){
local rawDataFolder=$1
local file folderName absFilePath
#get list of files
for file in `ls ${rawDataFolder}/*.N1`
do
  #folderName=`echo $file|cut -c23-30`
  folderName=`envisat_dump_header ${file} | awk '/^ABS_ORBIT /{printf "%s",$3}'`
  absFilePath=`canonicalPath ${file}`
  mkdir -p ${dataFolder}/${folderName} # create folder if missing
  ln -s "${absFilePath}" ${dataFolder}/${folderName}/
done

}

case "${1}" in 
"")
 all_scenes
 ;;
"exclude")
 shift
 scenes_exclude "$@"
 ;;
"include")
 shift
 scenes_include "$@"
 ;;
"init")
 shift
 scenes_init "$@"
 ;;
esac
