#!/bin/bash
# USAGE:
#	undo processName [fileName]
#	undo processName
#
# DESCRIPTION:
#  UNDO is an internal ADORE command. It removes the 
#  given processName from the result files.   
#
# INPUT:
#  processName: Doris step to be deleted from the resultfile.
#  
#  Optional:
#    fileName: If omitted undo will try to remove the given doris
#      step from master, slave and interferograms result files.    
#      If specified undo will only remove steps from the given file.
#
# OUTPUT:
#  Undo Successful: if doris step was found and removed.
#  
#

dorisProcessReset()
{
## AUTHOR:   Mahmut Arikan
## EMAIL:    M.Arikan@TUDelft.nl
## VERSION:  v1.4
## DATE:     20060612
## UPDATE:   20090114
##
## TUDelft, DEOS Radar Group  - 2006
##
##
## reset doris steps in the result files,
## up to the processing step you want
 
 lineno=$(awk '/_Start_'$1'/{print NR-1}' $2);  # get me the line number of the process line - 1
 if [ "$lineno" != "" ]; then 
   echo "  ${1} found at ${lineno} in ${2}"
   sed -i -e '/^'$1'/,/End_process_control/s/1/0/g' -e ''${lineno}',$ d' $2
   [ $? -eq 0 ] && echo "  Undo Successful."
 else
   echo "  ${1} not found in ${2}. This might not be important."
 fi
}

unset dorisStep
dorisStep=`pn2rs ${1}`

if [ "${2-undefined}" != "undefined" ]; then
  dorisProcessReset ${dorisStep} ${2}
elif [[ "${1}" == m_* ]]; then
  dorisProcessReset ${dorisStep} ${m_resfile};
elif [[ "${1}" == s_* ]]; then
  dorisProcessReset ${dorisStep} ${s_resfile}; 
else
  dorisProcessReset ${dorisStep} ${m_resfile}
  dorisProcessReset ${dorisStep} ${s_resfile}
  dorisProcessReset ${dorisStep} ${i_resfile}
fi

