#!/bin/bash
# This is another attempt to develop Automatic Doris Environment
# It runs like this:
# adore project.set dorisProcess
# default values are loaded from default.set
# each doris step can be run. They should have a corresponding *.drs file in the drs folder.

settings=${1}
dorisProcess=${2}

. ${settings} #load project settings
. "${ADOREFOLDER}/set/default.set" #load defaults.

#check if a special function exists in /scr/ folder
if [ -f "${ADOREFOLDER}/scr/${dorisProcess}" ]; then
	${ADOREFOLDER}/scr/${dorisProcess} ${settings}
else
	cat "${ADOREFOLDER}/drs/${dorisProcess}.drs" | while read line; do
		newline=`eval echo -E ${line}`
		echo $newline > ${outputFolder}/${dorisProcess}.drs
	done
fi
exit 0
