#!/bin/bash
# USAGE:
#	check
#	check resultFile
#
# DESCRIPTION:
#  CHECK is an internal ADORE command. 
#  It shows the process control list from the result files.
#
# INPUT:
#  No required inputs.
#   
#   Optional:
#     resultFile: If specified, only displays given files process control list.
#  
# OUTPUT:
#  Shows the process control list of given result file.
#

function displayProcessControl(){
  local startline=`grep -n Start_process_control ${1} | cut -f1 -d":"`
  local endline=`grep -n End_process_control ${1} | cut -f1 -d":"`

  local length=`echo ${endline} - ${startline} |bc`
  grep -A ${length} Start_process_control ${1} | grep -v "_process_control" | grep -v "NOT_USED"
}

local file1 file2 file3 files
files="";
if [ "${1:-undefined}" == "undefined" ]; then 
  #interferogram
  generateRandomString
  file3=${randomString}.tmp
  if [ -e ${i_resfile} ]; then
    echo -e "INTERFEROGRAM: \t\t" > ${file3}
    displayProcessControl ${i_resfile} >> ${file3}
    files+="${file3} "
  fi
  #master
  generateRandomString
  file1=${randomString}.tmp
  if [ -e ${m_resfile} ]; then
    echo -e "MASTER: \t\t" > ${file1}
    displayProcessControl ${m_resfile} >> ${file1}
    files+="${file1} "
  fi
  #slave
  generateRandomString
  file2=${randomString}.tmp
  if [ -e ${s_resfile} ];then 
    echo -e "SLAVE: \t\t" > ${file2}
    displayProcessControl ${s_resfile} >> ${file2}
    files+="${file2} "
  fi
#  echo ";"
  if [ -n "${files}" ]; then
    eval "paste ${files}"
    rm -rf ${files}
  else
    echo "No resultfiles can be found. Are you in the correct folder? Did you do any processing yet?"
  fi
else
  echo "${1}:"
  displayProcessControl ${1}
fi



