#!/bin/bash

# $0 dorisStep  
function export_envi(){
  dorisStep=${1}

  geocodeStatus=`check ${i_resfile} | grep -i -w "geocode"| cut -f2 -d:`
  if [ geocodeStatus ]; then
    (filename resfile format numpixels numlines)=dorisProcess2OutputFile ${dorisStep}
    (lfilename resfile format numpixels numlines)=dorisProcess2OutputFile ${dorisStep}
    

#get the coordinates for 1st px

#get the step size



<<COMMENTOUT
ENVI
description = {Registration Result. Method: Triangulation w/ cubic convolution [Fri Jan 22 17:23:16 2010]}
samples = ${samples}
lines   = ${length}
bands   = 1
header offset = 0
file type = ENVI Standard
data type = 2
interleave = bsq
sensor type = Unknown
byte order = 0
map info = {Geographic Lat/Lon, 1.0000, 1.0000, -107.87510370, 44.32640524, 3.7530213936e-04, 2.6998773854e-04, WGS-84, units=Degrees}
default bands = {1}
wavelength units = Unknown
band names = {Warp (DEM Elevation:bhdemsub.img)}
COMMENTOUT
