#!/bin/bash

function visualize_baselines(){
  ${ADOREFOLDER}/lib/python/plot_baselines.py ${baselinesFolder}/baselines
}

function visualize_fine(){
  ${ADOREFOLDER}/lib/python/plot_fine.py ${i_resfile}
}

function visualize_coarsecorr(){
  ${ADOREFOLDER}/lib/python/plot_coarsecorr.py ${i_resfile}
}

function visualize_map(){
  ${ADOREFOLDER}/lib/python/matshowclick_geocode.py ${i_resfile} ${@}
}

#################
## MAIN
#################

case ${1} in
  baselines)
    visualize_baselines
  ;; 
  coarsecorr)
    visualize_coarsecorr 
  ;;
  fine)
    visualize_fine
  ;;
  map)
    shift
    visualize_map ${@}
  ;;
  *)
    h visualize
  ;;
esac
